apiVersion: v1
kind: Namespace
metadata:
  name: vision
---

# configmap for the flask-based microservices
apiVersion: v1
kind: ConfigMap
metadata:
  name: vision-microservice-config-flask
  namespace: vision
data:
  TRACE_COLLECTOR_ENDPOINT: http://jaeger-with-cassandra-and-kafka-collector.observability.svc.cluster.local:4318
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vision-microservice-yolov8
  namespace: vision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vision-microservice-yolov8
  template:
    metadata:
      labels:
        app: vision-microservice-yolov8
    spec:
      containers:
      - name: vision-microservice-yolov8
        image: internationale/yolov8-onnx:latest
        envFrom:
          - configMapRef:
              name: vision-microservice-config-flask
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: myregistrykey
        # resources:
        #   limits:
        #     nvidia.com/gpu: 1
---

apiVersion: v1
kind: Service
metadata:
  name: vision-microservice-yolov8
  namespace: vision
spec:
  selector:
    app: vision-microservice-yolov8
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000