apiVersion: apps/v1
kind: Deployment
metadata:
  name: vision-microservice-yolov8
  namespace: vision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vision-microservice-yolov8
  template:
    metadata:
      labels:
        app: vision-microservice-yolov8
    spec:
      containers:
      - name: vision-microservice-yolov8
        image: internationale/yolov8-onnx:latest
        envFrom:
          - configMapRef:
              name: vision-microservice-config-flask
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: myregistrykey
        # resources:
        #   limits:
        #     nvidia.com/gpu: 1